
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DocumentFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DocumentFile
 * 
 */
export type DocumentFileModel = runtime.Types.Result.DefaultSelection<Prisma.$DocumentFilePayload>

export type AggregateDocumentFile = {
  _count: DocumentFileCountAggregateOutputType | null
  _min: DocumentFileMinAggregateOutputType | null
  _max: DocumentFileMaxAggregateOutputType | null
}

export type DocumentFileMinAggregateOutputType = {
  id: string | null
  documentId: string | null
  fileName: string | null
  fileType: string | null
  storagePath: string | null
  uploadedAt: Date | null
}

export type DocumentFileMaxAggregateOutputType = {
  id: string | null
  documentId: string | null
  fileName: string | null
  fileType: string | null
  storagePath: string | null
  uploadedAt: Date | null
}

export type DocumentFileCountAggregateOutputType = {
  id: number
  documentId: number
  fileName: number
  fileType: number
  storagePath: number
  uploadedAt: number
  _all: number
}


export type DocumentFileMinAggregateInputType = {
  id?: true
  documentId?: true
  fileName?: true
  fileType?: true
  storagePath?: true
  uploadedAt?: true
}

export type DocumentFileMaxAggregateInputType = {
  id?: true
  documentId?: true
  fileName?: true
  fileType?: true
  storagePath?: true
  uploadedAt?: true
}

export type DocumentFileCountAggregateInputType = {
  id?: true
  documentId?: true
  fileName?: true
  fileType?: true
  storagePath?: true
  uploadedAt?: true
  _all?: true
}

export type DocumentFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentFile to aggregate.
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentFiles to fetch.
   */
  orderBy?: Prisma.DocumentFileOrderByWithRelationInput | Prisma.DocumentFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DocumentFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DocumentFiles
  **/
  _count?: true | DocumentFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DocumentFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DocumentFileMaxAggregateInputType
}

export type GetDocumentFileAggregateType<T extends DocumentFileAggregateArgs> = {
      [P in keyof T & keyof AggregateDocumentFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDocumentFile[P]>
    : Prisma.GetScalarType<T[P], AggregateDocumentFile[P]>
}




export type DocumentFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentFileWhereInput
  orderBy?: Prisma.DocumentFileOrderByWithAggregationInput | Prisma.DocumentFileOrderByWithAggregationInput[]
  by: Prisma.DocumentFileScalarFieldEnum[] | Prisma.DocumentFileScalarFieldEnum
  having?: Prisma.DocumentFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DocumentFileCountAggregateInputType | true
  _min?: DocumentFileMinAggregateInputType
  _max?: DocumentFileMaxAggregateInputType
}

export type DocumentFileGroupByOutputType = {
  id: string
  documentId: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt: Date
  _count: DocumentFileCountAggregateOutputType | null
  _min: DocumentFileMinAggregateOutputType | null
  _max: DocumentFileMaxAggregateOutputType | null
}

type GetDocumentFileGroupByPayload<T extends DocumentFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DocumentFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DocumentFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DocumentFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DocumentFileGroupByOutputType[P]>
      }
    >
  >



export type DocumentFileWhereInput = {
  AND?: Prisma.DocumentFileWhereInput | Prisma.DocumentFileWhereInput[]
  OR?: Prisma.DocumentFileWhereInput[]
  NOT?: Prisma.DocumentFileWhereInput | Prisma.DocumentFileWhereInput[]
  id?: Prisma.StringFilter<"DocumentFile"> | string
  documentId?: Prisma.StringFilter<"DocumentFile"> | string
  fileName?: Prisma.StringFilter<"DocumentFile"> | string
  fileType?: Prisma.StringFilter<"DocumentFile"> | string
  storagePath?: Prisma.StringFilter<"DocumentFile"> | string
  uploadedAt?: Prisma.DateTimeFilter<"DocumentFile"> | Date | string
  document?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
}

export type DocumentFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  storagePath?: Prisma.SortOrder
  uploadedAt?: Prisma.SortOrder
  document?: Prisma.DocumentOrderByWithRelationInput
}

export type DocumentFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DocumentFileWhereInput | Prisma.DocumentFileWhereInput[]
  OR?: Prisma.DocumentFileWhereInput[]
  NOT?: Prisma.DocumentFileWhereInput | Prisma.DocumentFileWhereInput[]
  documentId?: Prisma.StringFilter<"DocumentFile"> | string
  fileName?: Prisma.StringFilter<"DocumentFile"> | string
  fileType?: Prisma.StringFilter<"DocumentFile"> | string
  storagePath?: Prisma.StringFilter<"DocumentFile"> | string
  uploadedAt?: Prisma.DateTimeFilter<"DocumentFile"> | Date | string
  document?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
}, "id">

export type DocumentFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  storagePath?: Prisma.SortOrder
  uploadedAt?: Prisma.SortOrder
  _count?: Prisma.DocumentFileCountOrderByAggregateInput
  _max?: Prisma.DocumentFileMaxOrderByAggregateInput
  _min?: Prisma.DocumentFileMinOrderByAggregateInput
}

export type DocumentFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.DocumentFileScalarWhereWithAggregatesInput | Prisma.DocumentFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.DocumentFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DocumentFileScalarWhereWithAggregatesInput | Prisma.DocumentFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DocumentFile"> | string
  documentId?: Prisma.StringWithAggregatesFilter<"DocumentFile"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"DocumentFile"> | string
  fileType?: Prisma.StringWithAggregatesFilter<"DocumentFile"> | string
  storagePath?: Prisma.StringWithAggregatesFilter<"DocumentFile"> | string
  uploadedAt?: Prisma.DateTimeWithAggregatesFilter<"DocumentFile"> | Date | string
}

export type DocumentFileCreateInput = {
  id?: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt?: Date | string
  document: Prisma.DocumentCreateNestedOneWithoutFilesInput
}

export type DocumentFileUncheckedCreateInput = {
  id?: string
  documentId: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt?: Date | string
}

export type DocumentFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  document?: Prisma.DocumentUpdateOneRequiredWithoutFilesNestedInput
}

export type DocumentFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentFileCreateManyInput = {
  id?: string
  documentId: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt?: Date | string
}

export type DocumentFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  storagePath?: Prisma.SortOrder
  uploadedAt?: Prisma.SortOrder
}

export type DocumentFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  storagePath?: Prisma.SortOrder
  uploadedAt?: Prisma.SortOrder
}

export type DocumentFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  storagePath?: Prisma.SortOrder
  uploadedAt?: Prisma.SortOrder
}

export type DocumentFileListRelationFilter = {
  every?: Prisma.DocumentFileWhereInput
  some?: Prisma.DocumentFileWhereInput
  none?: Prisma.DocumentFileWhereInput
}

export type DocumentFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type DocumentFileCreateNestedManyWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.DocumentFileCreateWithoutDocumentInput, Prisma.DocumentFileUncheckedCreateWithoutDocumentInput> | Prisma.DocumentFileCreateWithoutDocumentInput[] | Prisma.DocumentFileUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.DocumentFileCreateOrConnectWithoutDocumentInput | Prisma.DocumentFileCreateOrConnectWithoutDocumentInput[]
  createMany?: Prisma.DocumentFileCreateManyDocumentInputEnvelope
  connect?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
}

export type DocumentFileUncheckedCreateNestedManyWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.DocumentFileCreateWithoutDocumentInput, Prisma.DocumentFileUncheckedCreateWithoutDocumentInput> | Prisma.DocumentFileCreateWithoutDocumentInput[] | Prisma.DocumentFileUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.DocumentFileCreateOrConnectWithoutDocumentInput | Prisma.DocumentFileCreateOrConnectWithoutDocumentInput[]
  createMany?: Prisma.DocumentFileCreateManyDocumentInputEnvelope
  connect?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
}

export type DocumentFileUpdateManyWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentFileCreateWithoutDocumentInput, Prisma.DocumentFileUncheckedCreateWithoutDocumentInput> | Prisma.DocumentFileCreateWithoutDocumentInput[] | Prisma.DocumentFileUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.DocumentFileCreateOrConnectWithoutDocumentInput | Prisma.DocumentFileCreateOrConnectWithoutDocumentInput[]
  upsert?: Prisma.DocumentFileUpsertWithWhereUniqueWithoutDocumentInput | Prisma.DocumentFileUpsertWithWhereUniqueWithoutDocumentInput[]
  createMany?: Prisma.DocumentFileCreateManyDocumentInputEnvelope
  set?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  disconnect?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  delete?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  connect?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  update?: Prisma.DocumentFileUpdateWithWhereUniqueWithoutDocumentInput | Prisma.DocumentFileUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.DocumentFileUpdateManyWithWhereWithoutDocumentInput | Prisma.DocumentFileUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.DocumentFileScalarWhereInput | Prisma.DocumentFileScalarWhereInput[]
}

export type DocumentFileUncheckedUpdateManyWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentFileCreateWithoutDocumentInput, Prisma.DocumentFileUncheckedCreateWithoutDocumentInput> | Prisma.DocumentFileCreateWithoutDocumentInput[] | Prisma.DocumentFileUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.DocumentFileCreateOrConnectWithoutDocumentInput | Prisma.DocumentFileCreateOrConnectWithoutDocumentInput[]
  upsert?: Prisma.DocumentFileUpsertWithWhereUniqueWithoutDocumentInput | Prisma.DocumentFileUpsertWithWhereUniqueWithoutDocumentInput[]
  createMany?: Prisma.DocumentFileCreateManyDocumentInputEnvelope
  set?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  disconnect?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  delete?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  connect?: Prisma.DocumentFileWhereUniqueInput | Prisma.DocumentFileWhereUniqueInput[]
  update?: Prisma.DocumentFileUpdateWithWhereUniqueWithoutDocumentInput | Prisma.DocumentFileUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.DocumentFileUpdateManyWithWhereWithoutDocumentInput | Prisma.DocumentFileUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.DocumentFileScalarWhereInput | Prisma.DocumentFileScalarWhereInput[]
}

export type DocumentFileCreateWithoutDocumentInput = {
  id?: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt?: Date | string
}

export type DocumentFileUncheckedCreateWithoutDocumentInput = {
  id?: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt?: Date | string
}

export type DocumentFileCreateOrConnectWithoutDocumentInput = {
  where: Prisma.DocumentFileWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentFileCreateWithoutDocumentInput, Prisma.DocumentFileUncheckedCreateWithoutDocumentInput>
}

export type DocumentFileCreateManyDocumentInputEnvelope = {
  data: Prisma.DocumentFileCreateManyDocumentInput | Prisma.DocumentFileCreateManyDocumentInput[]
  skipDuplicates?: boolean
}

export type DocumentFileUpsertWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.DocumentFileWhereUniqueInput
  update: Prisma.XOR<Prisma.DocumentFileUpdateWithoutDocumentInput, Prisma.DocumentFileUncheckedUpdateWithoutDocumentInput>
  create: Prisma.XOR<Prisma.DocumentFileCreateWithoutDocumentInput, Prisma.DocumentFileUncheckedCreateWithoutDocumentInput>
}

export type DocumentFileUpdateWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.DocumentFileWhereUniqueInput
  data: Prisma.XOR<Prisma.DocumentFileUpdateWithoutDocumentInput, Prisma.DocumentFileUncheckedUpdateWithoutDocumentInput>
}

export type DocumentFileUpdateManyWithWhereWithoutDocumentInput = {
  where: Prisma.DocumentFileScalarWhereInput
  data: Prisma.XOR<Prisma.DocumentFileUpdateManyMutationInput, Prisma.DocumentFileUncheckedUpdateManyWithoutDocumentInput>
}

export type DocumentFileScalarWhereInput = {
  AND?: Prisma.DocumentFileScalarWhereInput | Prisma.DocumentFileScalarWhereInput[]
  OR?: Prisma.DocumentFileScalarWhereInput[]
  NOT?: Prisma.DocumentFileScalarWhereInput | Prisma.DocumentFileScalarWhereInput[]
  id?: Prisma.StringFilter<"DocumentFile"> | string
  documentId?: Prisma.StringFilter<"DocumentFile"> | string
  fileName?: Prisma.StringFilter<"DocumentFile"> | string
  fileType?: Prisma.StringFilter<"DocumentFile"> | string
  storagePath?: Prisma.StringFilter<"DocumentFile"> | string
  uploadedAt?: Prisma.DateTimeFilter<"DocumentFile"> | Date | string
}

export type DocumentFileCreateManyDocumentInput = {
  id?: string
  fileName: string
  fileType: string
  storagePath: string
  uploadedAt?: Date | string
}

export type DocumentFileUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentFileUncheckedUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentFileUncheckedUpdateManyWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  storagePath?: Prisma.StringFieldUpdateOperationsInput | string
  uploadedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DocumentFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  fileName?: boolean
  fileType?: boolean
  storagePath?: boolean
  uploadedAt?: boolean
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentFile"]>

export type DocumentFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  fileName?: boolean
  fileType?: boolean
  storagePath?: boolean
  uploadedAt?: boolean
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentFile"]>

export type DocumentFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  fileName?: boolean
  fileType?: boolean
  storagePath?: boolean
  uploadedAt?: boolean
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentFile"]>

export type DocumentFileSelectScalar = {
  id?: boolean
  documentId?: boolean
  fileName?: boolean
  fileType?: boolean
  storagePath?: boolean
  uploadedAt?: boolean
}

export type DocumentFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "documentId" | "fileName" | "fileType" | "storagePath" | "uploadedAt", ExtArgs["result"]["documentFile"]>
export type DocumentFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}
export type DocumentFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}
export type DocumentFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}

export type $DocumentFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DocumentFile"
  objects: {
    document: Prisma.$DocumentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    documentId: string
    fileName: string
    fileType: string
    storagePath: string
    uploadedAt: Date
  }, ExtArgs["result"]["documentFile"]>
  composites: {}
}

export type DocumentFileGetPayload<S extends boolean | null | undefined | DocumentFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload, S>

export type DocumentFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DocumentFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DocumentFileCountAggregateInputType | true
  }

export interface DocumentFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DocumentFile'], meta: { name: 'DocumentFile' } }
  /**
   * Find zero or one DocumentFile that matches the filter.
   * @param {DocumentFileFindUniqueArgs} args - Arguments to find a DocumentFile
   * @example
   * // Get one DocumentFile
   * const documentFile = await prisma.documentFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DocumentFileFindUniqueArgs>(args: Prisma.SelectSubset<T, DocumentFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DocumentFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DocumentFileFindUniqueOrThrowArgs} args - Arguments to find a DocumentFile
   * @example
   * // Get one DocumentFile
   * const documentFile = await prisma.documentFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DocumentFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DocumentFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileFindFirstArgs} args - Arguments to find a DocumentFile
   * @example
   * // Get one DocumentFile
   * const documentFile = await prisma.documentFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DocumentFileFindFirstArgs>(args?: Prisma.SelectSubset<T, DocumentFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileFindFirstOrThrowArgs} args - Arguments to find a DocumentFile
   * @example
   * // Get one DocumentFile
   * const documentFile = await prisma.documentFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DocumentFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DocumentFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DocumentFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DocumentFiles
   * const documentFiles = await prisma.documentFile.findMany()
   * 
   * // Get first 10 DocumentFiles
   * const documentFiles = await prisma.documentFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const documentFileWithIdOnly = await prisma.documentFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DocumentFileFindManyArgs>(args?: Prisma.SelectSubset<T, DocumentFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DocumentFile.
   * @param {DocumentFileCreateArgs} args - Arguments to create a DocumentFile.
   * @example
   * // Create one DocumentFile
   * const DocumentFile = await prisma.documentFile.create({
   *   data: {
   *     // ... data to create a DocumentFile
   *   }
   * })
   * 
   */
  create<T extends DocumentFileCreateArgs>(args: Prisma.SelectSubset<T, DocumentFileCreateArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DocumentFiles.
   * @param {DocumentFileCreateManyArgs} args - Arguments to create many DocumentFiles.
   * @example
   * // Create many DocumentFiles
   * const documentFile = await prisma.documentFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DocumentFileCreateManyArgs>(args?: Prisma.SelectSubset<T, DocumentFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DocumentFiles and returns the data saved in the database.
   * @param {DocumentFileCreateManyAndReturnArgs} args - Arguments to create many DocumentFiles.
   * @example
   * // Create many DocumentFiles
   * const documentFile = await prisma.documentFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DocumentFiles and only return the `id`
   * const documentFileWithIdOnly = await prisma.documentFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DocumentFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DocumentFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DocumentFile.
   * @param {DocumentFileDeleteArgs} args - Arguments to delete one DocumentFile.
   * @example
   * // Delete one DocumentFile
   * const DocumentFile = await prisma.documentFile.delete({
   *   where: {
   *     // ... filter to delete one DocumentFile
   *   }
   * })
   * 
   */
  delete<T extends DocumentFileDeleteArgs>(args: Prisma.SelectSubset<T, DocumentFileDeleteArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DocumentFile.
   * @param {DocumentFileUpdateArgs} args - Arguments to update one DocumentFile.
   * @example
   * // Update one DocumentFile
   * const documentFile = await prisma.documentFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DocumentFileUpdateArgs>(args: Prisma.SelectSubset<T, DocumentFileUpdateArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DocumentFiles.
   * @param {DocumentFileDeleteManyArgs} args - Arguments to filter DocumentFiles to delete.
   * @example
   * // Delete a few DocumentFiles
   * const { count } = await prisma.documentFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DocumentFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, DocumentFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DocumentFiles
   * const documentFile = await prisma.documentFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DocumentFileUpdateManyArgs>(args: Prisma.SelectSubset<T, DocumentFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentFiles and returns the data updated in the database.
   * @param {DocumentFileUpdateManyAndReturnArgs} args - Arguments to update many DocumentFiles.
   * @example
   * // Update many DocumentFiles
   * const documentFile = await prisma.documentFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DocumentFiles and only return the `id`
   * const documentFileWithIdOnly = await prisma.documentFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DocumentFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DocumentFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DocumentFile.
   * @param {DocumentFileUpsertArgs} args - Arguments to update or create a DocumentFile.
   * @example
   * // Update or create a DocumentFile
   * const documentFile = await prisma.documentFile.upsert({
   *   create: {
   *     // ... data to create a DocumentFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DocumentFile we want to update
   *   }
   * })
   */
  upsert<T extends DocumentFileUpsertArgs>(args: Prisma.SelectSubset<T, DocumentFileUpsertArgs<ExtArgs>>): Prisma.Prisma__DocumentFileClient<runtime.Types.Result.GetResult<Prisma.$DocumentFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DocumentFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileCountArgs} args - Arguments to filter DocumentFiles to count.
   * @example
   * // Count the number of DocumentFiles
   * const count = await prisma.documentFile.count({
   *   where: {
   *     // ... the filter for the DocumentFiles we want to count
   *   }
   * })
  **/
  count<T extends DocumentFileCountArgs>(
    args?: Prisma.Subset<T, DocumentFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DocumentFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DocumentFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DocumentFileAggregateArgs>(args: Prisma.Subset<T, DocumentFileAggregateArgs>): Prisma.PrismaPromise<GetDocumentFileAggregateType<T>>

  /**
   * Group by DocumentFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DocumentFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DocumentFileGroupByArgs['orderBy'] }
      : { orderBy?: DocumentFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DocumentFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDocumentFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DocumentFile model
 */
readonly fields: DocumentFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DocumentFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DocumentFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  document<T extends Prisma.DocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentClient<runtime.Types.Result.GetResult<Prisma.$DocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DocumentFile model
 */
export interface DocumentFileFieldRefs {
  readonly id: Prisma.FieldRef<"DocumentFile", 'String'>
  readonly documentId: Prisma.FieldRef<"DocumentFile", 'String'>
  readonly fileName: Prisma.FieldRef<"DocumentFile", 'String'>
  readonly fileType: Prisma.FieldRef<"DocumentFile", 'String'>
  readonly storagePath: Prisma.FieldRef<"DocumentFile", 'String'>
  readonly uploadedAt: Prisma.FieldRef<"DocumentFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DocumentFile findUnique
 */
export type DocumentFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * Filter, which DocumentFile to fetch.
   */
  where: Prisma.DocumentFileWhereUniqueInput
}

/**
 * DocumentFile findUniqueOrThrow
 */
export type DocumentFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * Filter, which DocumentFile to fetch.
   */
  where: Prisma.DocumentFileWhereUniqueInput
}

/**
 * DocumentFile findFirst
 */
export type DocumentFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * Filter, which DocumentFile to fetch.
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentFiles to fetch.
   */
  orderBy?: Prisma.DocumentFileOrderByWithRelationInput | Prisma.DocumentFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentFiles.
   */
  cursor?: Prisma.DocumentFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentFiles.
   */
  distinct?: Prisma.DocumentFileScalarFieldEnum | Prisma.DocumentFileScalarFieldEnum[]
}

/**
 * DocumentFile findFirstOrThrow
 */
export type DocumentFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * Filter, which DocumentFile to fetch.
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentFiles to fetch.
   */
  orderBy?: Prisma.DocumentFileOrderByWithRelationInput | Prisma.DocumentFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentFiles.
   */
  cursor?: Prisma.DocumentFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentFiles.
   */
  distinct?: Prisma.DocumentFileScalarFieldEnum | Prisma.DocumentFileScalarFieldEnum[]
}

/**
 * DocumentFile findMany
 */
export type DocumentFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * Filter, which DocumentFiles to fetch.
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentFiles to fetch.
   */
  orderBy?: Prisma.DocumentFileOrderByWithRelationInput | Prisma.DocumentFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DocumentFiles.
   */
  cursor?: Prisma.DocumentFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentFiles.
   */
  skip?: number
  distinct?: Prisma.DocumentFileScalarFieldEnum | Prisma.DocumentFileScalarFieldEnum[]
}

/**
 * DocumentFile create
 */
export type DocumentFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * The data needed to create a DocumentFile.
   */
  data: Prisma.XOR<Prisma.DocumentFileCreateInput, Prisma.DocumentFileUncheckedCreateInput>
}

/**
 * DocumentFile createMany
 */
export type DocumentFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DocumentFiles.
   */
  data: Prisma.DocumentFileCreateManyInput | Prisma.DocumentFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DocumentFile createManyAndReturn
 */
export type DocumentFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * The data used to create many DocumentFiles.
   */
  data: Prisma.DocumentFileCreateManyInput | Prisma.DocumentFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DocumentFile update
 */
export type DocumentFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * The data needed to update a DocumentFile.
   */
  data: Prisma.XOR<Prisma.DocumentFileUpdateInput, Prisma.DocumentFileUncheckedUpdateInput>
  /**
   * Choose, which DocumentFile to update.
   */
  where: Prisma.DocumentFileWhereUniqueInput
}

/**
 * DocumentFile updateMany
 */
export type DocumentFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DocumentFiles.
   */
  data: Prisma.XOR<Prisma.DocumentFileUpdateManyMutationInput, Prisma.DocumentFileUncheckedUpdateManyInput>
  /**
   * Filter which DocumentFiles to update
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * Limit how many DocumentFiles to update.
   */
  limit?: number
}

/**
 * DocumentFile updateManyAndReturn
 */
export type DocumentFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * The data used to update DocumentFiles.
   */
  data: Prisma.XOR<Prisma.DocumentFileUpdateManyMutationInput, Prisma.DocumentFileUncheckedUpdateManyInput>
  /**
   * Filter which DocumentFiles to update
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * Limit how many DocumentFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DocumentFile upsert
 */
export type DocumentFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * The filter to search for the DocumentFile to update in case it exists.
   */
  where: Prisma.DocumentFileWhereUniqueInput
  /**
   * In case the DocumentFile found by the `where` argument doesn't exist, create a new DocumentFile with this data.
   */
  create: Prisma.XOR<Prisma.DocumentFileCreateInput, Prisma.DocumentFileUncheckedCreateInput>
  /**
   * In case the DocumentFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DocumentFileUpdateInput, Prisma.DocumentFileUncheckedUpdateInput>
}

/**
 * DocumentFile delete
 */
export type DocumentFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
  /**
   * Filter which DocumentFile to delete.
   */
  where: Prisma.DocumentFileWhereUniqueInput
}

/**
 * DocumentFile deleteMany
 */
export type DocumentFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentFiles to delete
   */
  where?: Prisma.DocumentFileWhereInput
  /**
   * Limit how many DocumentFiles to delete.
   */
  limit?: number
}

/**
 * DocumentFile without action
 */
export type DocumentFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentFile
   */
  select?: Prisma.DocumentFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentFile
   */
  omit?: Prisma.DocumentFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentFileInclude<ExtArgs> | null
}
