
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DocumentPair` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DocumentPair
 * 
 */
export type DocumentPairModel = runtime.Types.Result.DefaultSelection<Prisma.$DocumentPairPayload>

export type AggregateDocumentPair = {
  _count: DocumentPairCountAggregateOutputType | null
  _min: DocumentPairMinAggregateOutputType | null
  _max: DocumentPairMaxAggregateOutputType | null
}

export type DocumentPairMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  invoiceId: string | null
  createdAt: Date | null
}

export type DocumentPairMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  invoiceId: string | null
  createdAt: Date | null
}

export type DocumentPairCountAggregateOutputType = {
  id: number
  orderId: number
  invoiceId: number
  createdAt: number
  _all: number
}


export type DocumentPairMinAggregateInputType = {
  id?: true
  orderId?: true
  invoiceId?: true
  createdAt?: true
}

export type DocumentPairMaxAggregateInputType = {
  id?: true
  orderId?: true
  invoiceId?: true
  createdAt?: true
}

export type DocumentPairCountAggregateInputType = {
  id?: true
  orderId?: true
  invoiceId?: true
  createdAt?: true
  _all?: true
}

export type DocumentPairAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentPair to aggregate.
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentPairs to fetch.
   */
  orderBy?: Prisma.DocumentPairOrderByWithRelationInput | Prisma.DocumentPairOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DocumentPairWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentPairs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentPairs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DocumentPairs
  **/
  _count?: true | DocumentPairCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DocumentPairMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DocumentPairMaxAggregateInputType
}

export type GetDocumentPairAggregateType<T extends DocumentPairAggregateArgs> = {
      [P in keyof T & keyof AggregateDocumentPair]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDocumentPair[P]>
    : Prisma.GetScalarType<T[P], AggregateDocumentPair[P]>
}




export type DocumentPairGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentPairWhereInput
  orderBy?: Prisma.DocumentPairOrderByWithAggregationInput | Prisma.DocumentPairOrderByWithAggregationInput[]
  by: Prisma.DocumentPairScalarFieldEnum[] | Prisma.DocumentPairScalarFieldEnum
  having?: Prisma.DocumentPairScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DocumentPairCountAggregateInputType | true
  _min?: DocumentPairMinAggregateInputType
  _max?: DocumentPairMaxAggregateInputType
}

export type DocumentPairGroupByOutputType = {
  id: string
  orderId: string
  invoiceId: string
  createdAt: Date
  _count: DocumentPairCountAggregateOutputType | null
  _min: DocumentPairMinAggregateOutputType | null
  _max: DocumentPairMaxAggregateOutputType | null
}

type GetDocumentPairGroupByPayload<T extends DocumentPairGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DocumentPairGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DocumentPairGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DocumentPairGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DocumentPairGroupByOutputType[P]>
      }
    >
  >



export type DocumentPairWhereInput = {
  AND?: Prisma.DocumentPairWhereInput | Prisma.DocumentPairWhereInput[]
  OR?: Prisma.DocumentPairWhereInput[]
  NOT?: Prisma.DocumentPairWhereInput | Prisma.DocumentPairWhereInput[]
  id?: Prisma.StringFilter<"DocumentPair"> | string
  orderId?: Prisma.StringFilter<"DocumentPair"> | string
  invoiceId?: Prisma.StringFilter<"DocumentPair"> | string
  createdAt?: Prisma.DateTimeFilter<"DocumentPair"> | Date | string
  order?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
  invoice?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
  validations?: Prisma.ValidationResultListRelationFilter
  summary?: Prisma.XOR<Prisma.ValidationSummaryNullableScalarRelationFilter, Prisma.ValidationSummaryWhereInput> | null
}

export type DocumentPairOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  invoiceId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  order?: Prisma.DocumentOrderByWithRelationInput
  invoice?: Prisma.DocumentOrderByWithRelationInput
  validations?: Prisma.ValidationResultOrderByRelationAggregateInput
  summary?: Prisma.ValidationSummaryOrderByWithRelationInput
}

export type DocumentPairWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DocumentPairWhereInput | Prisma.DocumentPairWhereInput[]
  OR?: Prisma.DocumentPairWhereInput[]
  NOT?: Prisma.DocumentPairWhereInput | Prisma.DocumentPairWhereInput[]
  orderId?: Prisma.StringFilter<"DocumentPair"> | string
  invoiceId?: Prisma.StringFilter<"DocumentPair"> | string
  createdAt?: Prisma.DateTimeFilter<"DocumentPair"> | Date | string
  order?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
  invoice?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
  validations?: Prisma.ValidationResultListRelationFilter
  summary?: Prisma.XOR<Prisma.ValidationSummaryNullableScalarRelationFilter, Prisma.ValidationSummaryWhereInput> | null
}, "id">

export type DocumentPairOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  invoiceId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DocumentPairCountOrderByAggregateInput
  _max?: Prisma.DocumentPairMaxOrderByAggregateInput
  _min?: Prisma.DocumentPairMinOrderByAggregateInput
}

export type DocumentPairScalarWhereWithAggregatesInput = {
  AND?: Prisma.DocumentPairScalarWhereWithAggregatesInput | Prisma.DocumentPairScalarWhereWithAggregatesInput[]
  OR?: Prisma.DocumentPairScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DocumentPairScalarWhereWithAggregatesInput | Prisma.DocumentPairScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DocumentPair"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"DocumentPair"> | string
  invoiceId?: Prisma.StringWithAggregatesFilter<"DocumentPair"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DocumentPair"> | Date | string
}

export type DocumentPairCreateInput = {
  id?: string
  createdAt?: Date | string
  order: Prisma.DocumentCreateNestedOneWithoutOrderPairsInput
  invoice: Prisma.DocumentCreateNestedOneWithoutInvoicePairsInput
  validations?: Prisma.ValidationResultCreateNestedManyWithoutPairInput
  summary?: Prisma.ValidationSummaryCreateNestedOneWithoutPairInput
}

export type DocumentPairUncheckedCreateInput = {
  id?: string
  orderId: string
  invoiceId: string
  createdAt?: Date | string
  validations?: Prisma.ValidationResultUncheckedCreateNestedManyWithoutPairInput
  summary?: Prisma.ValidationSummaryUncheckedCreateNestedOneWithoutPairInput
}

export type DocumentPairUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.DocumentUpdateOneRequiredWithoutOrderPairsNestedInput
  invoice?: Prisma.DocumentUpdateOneRequiredWithoutInvoicePairsNestedInput
  validations?: Prisma.ValidationResultUpdateManyWithoutPairNestedInput
  summary?: Prisma.ValidationSummaryUpdateOneWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  invoiceId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validations?: Prisma.ValidationResultUncheckedUpdateManyWithoutPairNestedInput
  summary?: Prisma.ValidationSummaryUncheckedUpdateOneWithoutPairNestedInput
}

export type DocumentPairCreateManyInput = {
  id?: string
  orderId: string
  invoiceId: string
  createdAt?: Date | string
}

export type DocumentPairUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentPairUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  invoiceId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentPairListRelationFilter = {
  every?: Prisma.DocumentPairWhereInput
  some?: Prisma.DocumentPairWhereInput
  none?: Prisma.DocumentPairWhereInput
}

export type DocumentPairOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DocumentPairCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  invoiceId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DocumentPairMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  invoiceId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DocumentPairMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  invoiceId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DocumentPairScalarRelationFilter = {
  is?: Prisma.DocumentPairWhereInput
  isNot?: Prisma.DocumentPairWhereInput
}

export type DocumentPairCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutOrderInput, Prisma.DocumentPairUncheckedCreateWithoutOrderInput> | Prisma.DocumentPairCreateWithoutOrderInput[] | Prisma.DocumentPairUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutOrderInput | Prisma.DocumentPairCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.DocumentPairCreateManyOrderInputEnvelope
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
}

export type DocumentPairCreateNestedManyWithoutInvoiceInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutInvoiceInput, Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput> | Prisma.DocumentPairCreateWithoutInvoiceInput[] | Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput | Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput[]
  createMany?: Prisma.DocumentPairCreateManyInvoiceInputEnvelope
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
}

export type DocumentPairUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutOrderInput, Prisma.DocumentPairUncheckedCreateWithoutOrderInput> | Prisma.DocumentPairCreateWithoutOrderInput[] | Prisma.DocumentPairUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutOrderInput | Prisma.DocumentPairCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.DocumentPairCreateManyOrderInputEnvelope
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
}

export type DocumentPairUncheckedCreateNestedManyWithoutInvoiceInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutInvoiceInput, Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput> | Prisma.DocumentPairCreateWithoutInvoiceInput[] | Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput | Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput[]
  createMany?: Prisma.DocumentPairCreateManyInvoiceInputEnvelope
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
}

export type DocumentPairUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutOrderInput, Prisma.DocumentPairUncheckedCreateWithoutOrderInput> | Prisma.DocumentPairCreateWithoutOrderInput[] | Prisma.DocumentPairUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutOrderInput | Prisma.DocumentPairCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.DocumentPairUpsertWithWhereUniqueWithoutOrderInput | Prisma.DocumentPairUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.DocumentPairCreateManyOrderInputEnvelope
  set?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  disconnect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  delete?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  update?: Prisma.DocumentPairUpdateWithWhereUniqueWithoutOrderInput | Prisma.DocumentPairUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.DocumentPairUpdateManyWithWhereWithoutOrderInput | Prisma.DocumentPairUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.DocumentPairScalarWhereInput | Prisma.DocumentPairScalarWhereInput[]
}

export type DocumentPairUpdateManyWithoutInvoiceNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutInvoiceInput, Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput> | Prisma.DocumentPairCreateWithoutInvoiceInput[] | Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput | Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput[]
  upsert?: Prisma.DocumentPairUpsertWithWhereUniqueWithoutInvoiceInput | Prisma.DocumentPairUpsertWithWhereUniqueWithoutInvoiceInput[]
  createMany?: Prisma.DocumentPairCreateManyInvoiceInputEnvelope
  set?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  disconnect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  delete?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  update?: Prisma.DocumentPairUpdateWithWhereUniqueWithoutInvoiceInput | Prisma.DocumentPairUpdateWithWhereUniqueWithoutInvoiceInput[]
  updateMany?: Prisma.DocumentPairUpdateManyWithWhereWithoutInvoiceInput | Prisma.DocumentPairUpdateManyWithWhereWithoutInvoiceInput[]
  deleteMany?: Prisma.DocumentPairScalarWhereInput | Prisma.DocumentPairScalarWhereInput[]
}

export type DocumentPairUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutOrderInput, Prisma.DocumentPairUncheckedCreateWithoutOrderInput> | Prisma.DocumentPairCreateWithoutOrderInput[] | Prisma.DocumentPairUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutOrderInput | Prisma.DocumentPairCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.DocumentPairUpsertWithWhereUniqueWithoutOrderInput | Prisma.DocumentPairUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.DocumentPairCreateManyOrderInputEnvelope
  set?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  disconnect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  delete?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  update?: Prisma.DocumentPairUpdateWithWhereUniqueWithoutOrderInput | Prisma.DocumentPairUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.DocumentPairUpdateManyWithWhereWithoutOrderInput | Prisma.DocumentPairUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.DocumentPairScalarWhereInput | Prisma.DocumentPairScalarWhereInput[]
}

export type DocumentPairUncheckedUpdateManyWithoutInvoiceNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutInvoiceInput, Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput> | Prisma.DocumentPairCreateWithoutInvoiceInput[] | Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput[]
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput | Prisma.DocumentPairCreateOrConnectWithoutInvoiceInput[]
  upsert?: Prisma.DocumentPairUpsertWithWhereUniqueWithoutInvoiceInput | Prisma.DocumentPairUpsertWithWhereUniqueWithoutInvoiceInput[]
  createMany?: Prisma.DocumentPairCreateManyInvoiceInputEnvelope
  set?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  disconnect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  delete?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  connect?: Prisma.DocumentPairWhereUniqueInput | Prisma.DocumentPairWhereUniqueInput[]
  update?: Prisma.DocumentPairUpdateWithWhereUniqueWithoutInvoiceInput | Prisma.DocumentPairUpdateWithWhereUniqueWithoutInvoiceInput[]
  updateMany?: Prisma.DocumentPairUpdateManyWithWhereWithoutInvoiceInput | Prisma.DocumentPairUpdateManyWithWhereWithoutInvoiceInput[]
  deleteMany?: Prisma.DocumentPairScalarWhereInput | Prisma.DocumentPairScalarWhereInput[]
}

export type DocumentPairCreateNestedOneWithoutValidationsInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutValidationsInput, Prisma.DocumentPairUncheckedCreateWithoutValidationsInput>
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutValidationsInput
  connect?: Prisma.DocumentPairWhereUniqueInput
}

export type DocumentPairUpdateOneRequiredWithoutValidationsNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutValidationsInput, Prisma.DocumentPairUncheckedCreateWithoutValidationsInput>
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutValidationsInput
  upsert?: Prisma.DocumentPairUpsertWithoutValidationsInput
  connect?: Prisma.DocumentPairWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DocumentPairUpdateToOneWithWhereWithoutValidationsInput, Prisma.DocumentPairUpdateWithoutValidationsInput>, Prisma.DocumentPairUncheckedUpdateWithoutValidationsInput>
}

export type DocumentPairCreateNestedOneWithoutSummaryInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutSummaryInput, Prisma.DocumentPairUncheckedCreateWithoutSummaryInput>
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutSummaryInput
  connect?: Prisma.DocumentPairWhereUniqueInput
}

export type DocumentPairUpdateOneRequiredWithoutSummaryNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentPairCreateWithoutSummaryInput, Prisma.DocumentPairUncheckedCreateWithoutSummaryInput>
  connectOrCreate?: Prisma.DocumentPairCreateOrConnectWithoutSummaryInput
  upsert?: Prisma.DocumentPairUpsertWithoutSummaryInput
  connect?: Prisma.DocumentPairWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DocumentPairUpdateToOneWithWhereWithoutSummaryInput, Prisma.DocumentPairUpdateWithoutSummaryInput>, Prisma.DocumentPairUncheckedUpdateWithoutSummaryInput>
}

export type DocumentPairCreateWithoutOrderInput = {
  id?: string
  createdAt?: Date | string
  invoice: Prisma.DocumentCreateNestedOneWithoutInvoicePairsInput
  validations?: Prisma.ValidationResultCreateNestedManyWithoutPairInput
  summary?: Prisma.ValidationSummaryCreateNestedOneWithoutPairInput
}

export type DocumentPairUncheckedCreateWithoutOrderInput = {
  id?: string
  invoiceId: string
  createdAt?: Date | string
  validations?: Prisma.ValidationResultUncheckedCreateNestedManyWithoutPairInput
  summary?: Prisma.ValidationSummaryUncheckedCreateNestedOneWithoutPairInput
}

export type DocumentPairCreateOrConnectWithoutOrderInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutOrderInput, Prisma.DocumentPairUncheckedCreateWithoutOrderInput>
}

export type DocumentPairCreateManyOrderInputEnvelope = {
  data: Prisma.DocumentPairCreateManyOrderInput | Prisma.DocumentPairCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type DocumentPairCreateWithoutInvoiceInput = {
  id?: string
  createdAt?: Date | string
  order: Prisma.DocumentCreateNestedOneWithoutOrderPairsInput
  validations?: Prisma.ValidationResultCreateNestedManyWithoutPairInput
  summary?: Prisma.ValidationSummaryCreateNestedOneWithoutPairInput
}

export type DocumentPairUncheckedCreateWithoutInvoiceInput = {
  id?: string
  orderId: string
  createdAt?: Date | string
  validations?: Prisma.ValidationResultUncheckedCreateNestedManyWithoutPairInput
  summary?: Prisma.ValidationSummaryUncheckedCreateNestedOneWithoutPairInput
}

export type DocumentPairCreateOrConnectWithoutInvoiceInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutInvoiceInput, Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput>
}

export type DocumentPairCreateManyInvoiceInputEnvelope = {
  data: Prisma.DocumentPairCreateManyInvoiceInput | Prisma.DocumentPairCreateManyInvoiceInput[]
  skipDuplicates?: boolean
}

export type DocumentPairUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  update: Prisma.XOR<Prisma.DocumentPairUpdateWithoutOrderInput, Prisma.DocumentPairUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutOrderInput, Prisma.DocumentPairUncheckedCreateWithoutOrderInput>
}

export type DocumentPairUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  data: Prisma.XOR<Prisma.DocumentPairUpdateWithoutOrderInput, Prisma.DocumentPairUncheckedUpdateWithoutOrderInput>
}

export type DocumentPairUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.DocumentPairScalarWhereInput
  data: Prisma.XOR<Prisma.DocumentPairUpdateManyMutationInput, Prisma.DocumentPairUncheckedUpdateManyWithoutOrderInput>
}

export type DocumentPairScalarWhereInput = {
  AND?: Prisma.DocumentPairScalarWhereInput | Prisma.DocumentPairScalarWhereInput[]
  OR?: Prisma.DocumentPairScalarWhereInput[]
  NOT?: Prisma.DocumentPairScalarWhereInput | Prisma.DocumentPairScalarWhereInput[]
  id?: Prisma.StringFilter<"DocumentPair"> | string
  orderId?: Prisma.StringFilter<"DocumentPair"> | string
  invoiceId?: Prisma.StringFilter<"DocumentPair"> | string
  createdAt?: Prisma.DateTimeFilter<"DocumentPair"> | Date | string
}

export type DocumentPairUpsertWithWhereUniqueWithoutInvoiceInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  update: Prisma.XOR<Prisma.DocumentPairUpdateWithoutInvoiceInput, Prisma.DocumentPairUncheckedUpdateWithoutInvoiceInput>
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutInvoiceInput, Prisma.DocumentPairUncheckedCreateWithoutInvoiceInput>
}

export type DocumentPairUpdateWithWhereUniqueWithoutInvoiceInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  data: Prisma.XOR<Prisma.DocumentPairUpdateWithoutInvoiceInput, Prisma.DocumentPairUncheckedUpdateWithoutInvoiceInput>
}

export type DocumentPairUpdateManyWithWhereWithoutInvoiceInput = {
  where: Prisma.DocumentPairScalarWhereInput
  data: Prisma.XOR<Prisma.DocumentPairUpdateManyMutationInput, Prisma.DocumentPairUncheckedUpdateManyWithoutInvoiceInput>
}

export type DocumentPairCreateWithoutValidationsInput = {
  id?: string
  createdAt?: Date | string
  order: Prisma.DocumentCreateNestedOneWithoutOrderPairsInput
  invoice: Prisma.DocumentCreateNestedOneWithoutInvoicePairsInput
  summary?: Prisma.ValidationSummaryCreateNestedOneWithoutPairInput
}

export type DocumentPairUncheckedCreateWithoutValidationsInput = {
  id?: string
  orderId: string
  invoiceId: string
  createdAt?: Date | string
  summary?: Prisma.ValidationSummaryUncheckedCreateNestedOneWithoutPairInput
}

export type DocumentPairCreateOrConnectWithoutValidationsInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutValidationsInput, Prisma.DocumentPairUncheckedCreateWithoutValidationsInput>
}

export type DocumentPairUpsertWithoutValidationsInput = {
  update: Prisma.XOR<Prisma.DocumentPairUpdateWithoutValidationsInput, Prisma.DocumentPairUncheckedUpdateWithoutValidationsInput>
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutValidationsInput, Prisma.DocumentPairUncheckedCreateWithoutValidationsInput>
  where?: Prisma.DocumentPairWhereInput
}

export type DocumentPairUpdateToOneWithWhereWithoutValidationsInput = {
  where?: Prisma.DocumentPairWhereInput
  data: Prisma.XOR<Prisma.DocumentPairUpdateWithoutValidationsInput, Prisma.DocumentPairUncheckedUpdateWithoutValidationsInput>
}

export type DocumentPairUpdateWithoutValidationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.DocumentUpdateOneRequiredWithoutOrderPairsNestedInput
  invoice?: Prisma.DocumentUpdateOneRequiredWithoutInvoicePairsNestedInput
  summary?: Prisma.ValidationSummaryUpdateOneWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateWithoutValidationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  invoiceId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  summary?: Prisma.ValidationSummaryUncheckedUpdateOneWithoutPairNestedInput
}

export type DocumentPairCreateWithoutSummaryInput = {
  id?: string
  createdAt?: Date | string
  order: Prisma.DocumentCreateNestedOneWithoutOrderPairsInput
  invoice: Prisma.DocumentCreateNestedOneWithoutInvoicePairsInput
  validations?: Prisma.ValidationResultCreateNestedManyWithoutPairInput
}

export type DocumentPairUncheckedCreateWithoutSummaryInput = {
  id?: string
  orderId: string
  invoiceId: string
  createdAt?: Date | string
  validations?: Prisma.ValidationResultUncheckedCreateNestedManyWithoutPairInput
}

export type DocumentPairCreateOrConnectWithoutSummaryInput = {
  where: Prisma.DocumentPairWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutSummaryInput, Prisma.DocumentPairUncheckedCreateWithoutSummaryInput>
}

export type DocumentPairUpsertWithoutSummaryInput = {
  update: Prisma.XOR<Prisma.DocumentPairUpdateWithoutSummaryInput, Prisma.DocumentPairUncheckedUpdateWithoutSummaryInput>
  create: Prisma.XOR<Prisma.DocumentPairCreateWithoutSummaryInput, Prisma.DocumentPairUncheckedCreateWithoutSummaryInput>
  where?: Prisma.DocumentPairWhereInput
}

export type DocumentPairUpdateToOneWithWhereWithoutSummaryInput = {
  where?: Prisma.DocumentPairWhereInput
  data: Prisma.XOR<Prisma.DocumentPairUpdateWithoutSummaryInput, Prisma.DocumentPairUncheckedUpdateWithoutSummaryInput>
}

export type DocumentPairUpdateWithoutSummaryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.DocumentUpdateOneRequiredWithoutOrderPairsNestedInput
  invoice?: Prisma.DocumentUpdateOneRequiredWithoutInvoicePairsNestedInput
  validations?: Prisma.ValidationResultUpdateManyWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateWithoutSummaryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  invoiceId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validations?: Prisma.ValidationResultUncheckedUpdateManyWithoutPairNestedInput
}

export type DocumentPairCreateManyOrderInput = {
  id?: string
  invoiceId: string
  createdAt?: Date | string
}

export type DocumentPairCreateManyInvoiceInput = {
  id?: string
  orderId: string
  createdAt?: Date | string
}

export type DocumentPairUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invoice?: Prisma.DocumentUpdateOneRequiredWithoutInvoicePairsNestedInput
  validations?: Prisma.ValidationResultUpdateManyWithoutPairNestedInput
  summary?: Prisma.ValidationSummaryUpdateOneWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  invoiceId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validations?: Prisma.ValidationResultUncheckedUpdateManyWithoutPairNestedInput
  summary?: Prisma.ValidationSummaryUncheckedUpdateOneWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  invoiceId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentPairUpdateWithoutInvoiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.DocumentUpdateOneRequiredWithoutOrderPairsNestedInput
  validations?: Prisma.ValidationResultUpdateManyWithoutPairNestedInput
  summary?: Prisma.ValidationSummaryUpdateOneWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateWithoutInvoiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validations?: Prisma.ValidationResultUncheckedUpdateManyWithoutPairNestedInput
  summary?: Prisma.ValidationSummaryUncheckedUpdateOneWithoutPairNestedInput
}

export type DocumentPairUncheckedUpdateManyWithoutInvoiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DocumentPairCountOutputType
 */

export type DocumentPairCountOutputType = {
  validations: number
}

export type DocumentPairCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  validations?: boolean | DocumentPairCountOutputTypeCountValidationsArgs
}

/**
 * DocumentPairCountOutputType without action
 */
export type DocumentPairCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPairCountOutputType
   */
  select?: Prisma.DocumentPairCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DocumentPairCountOutputType without action
 */
export type DocumentPairCountOutputTypeCountValidationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ValidationResultWhereInput
}


export type DocumentPairSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  invoiceId?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  invoice?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  validations?: boolean | Prisma.DocumentPair$validationsArgs<ExtArgs>
  summary?: boolean | Prisma.DocumentPair$summaryArgs<ExtArgs>
  _count?: boolean | Prisma.DocumentPairCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentPair"]>

export type DocumentPairSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  invoiceId?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  invoice?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentPair"]>

export type DocumentPairSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  invoiceId?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  invoice?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentPair"]>

export type DocumentPairSelectScalar = {
  id?: boolean
  orderId?: boolean
  invoiceId?: boolean
  createdAt?: boolean
}

export type DocumentPairOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "invoiceId" | "createdAt", ExtArgs["result"]["documentPair"]>
export type DocumentPairInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  invoice?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  validations?: boolean | Prisma.DocumentPair$validationsArgs<ExtArgs>
  summary?: boolean | Prisma.DocumentPair$summaryArgs<ExtArgs>
  _count?: boolean | Prisma.DocumentPairCountOutputTypeDefaultArgs<ExtArgs>
}
export type DocumentPairIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  invoice?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}
export type DocumentPairIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  invoice?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
}

export type $DocumentPairPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DocumentPair"
  objects: {
    order: Prisma.$DocumentPayload<ExtArgs>
    invoice: Prisma.$DocumentPayload<ExtArgs>
    validations: Prisma.$ValidationResultPayload<ExtArgs>[]
    summary: Prisma.$ValidationSummaryPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    invoiceId: string
    createdAt: Date
  }, ExtArgs["result"]["documentPair"]>
  composites: {}
}

export type DocumentPairGetPayload<S extends boolean | null | undefined | DocumentPairDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload, S>

export type DocumentPairCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DocumentPairFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DocumentPairCountAggregateInputType | true
  }

export interface DocumentPairDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DocumentPair'], meta: { name: 'DocumentPair' } }
  /**
   * Find zero or one DocumentPair that matches the filter.
   * @param {DocumentPairFindUniqueArgs} args - Arguments to find a DocumentPair
   * @example
   * // Get one DocumentPair
   * const documentPair = await prisma.documentPair.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DocumentPairFindUniqueArgs>(args: Prisma.SelectSubset<T, DocumentPairFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DocumentPair that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DocumentPairFindUniqueOrThrowArgs} args - Arguments to find a DocumentPair
   * @example
   * // Get one DocumentPair
   * const documentPair = await prisma.documentPair.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DocumentPairFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DocumentPairFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentPair that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairFindFirstArgs} args - Arguments to find a DocumentPair
   * @example
   * // Get one DocumentPair
   * const documentPair = await prisma.documentPair.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DocumentPairFindFirstArgs>(args?: Prisma.SelectSubset<T, DocumentPairFindFirstArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentPair that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairFindFirstOrThrowArgs} args - Arguments to find a DocumentPair
   * @example
   * // Get one DocumentPair
   * const documentPair = await prisma.documentPair.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DocumentPairFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DocumentPairFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DocumentPairs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DocumentPairs
   * const documentPairs = await prisma.documentPair.findMany()
   * 
   * // Get first 10 DocumentPairs
   * const documentPairs = await prisma.documentPair.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const documentPairWithIdOnly = await prisma.documentPair.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DocumentPairFindManyArgs>(args?: Prisma.SelectSubset<T, DocumentPairFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DocumentPair.
   * @param {DocumentPairCreateArgs} args - Arguments to create a DocumentPair.
   * @example
   * // Create one DocumentPair
   * const DocumentPair = await prisma.documentPair.create({
   *   data: {
   *     // ... data to create a DocumentPair
   *   }
   * })
   * 
   */
  create<T extends DocumentPairCreateArgs>(args: Prisma.SelectSubset<T, DocumentPairCreateArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DocumentPairs.
   * @param {DocumentPairCreateManyArgs} args - Arguments to create many DocumentPairs.
   * @example
   * // Create many DocumentPairs
   * const documentPair = await prisma.documentPair.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DocumentPairCreateManyArgs>(args?: Prisma.SelectSubset<T, DocumentPairCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DocumentPairs and returns the data saved in the database.
   * @param {DocumentPairCreateManyAndReturnArgs} args - Arguments to create many DocumentPairs.
   * @example
   * // Create many DocumentPairs
   * const documentPair = await prisma.documentPair.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DocumentPairs and only return the `id`
   * const documentPairWithIdOnly = await prisma.documentPair.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DocumentPairCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DocumentPairCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DocumentPair.
   * @param {DocumentPairDeleteArgs} args - Arguments to delete one DocumentPair.
   * @example
   * // Delete one DocumentPair
   * const DocumentPair = await prisma.documentPair.delete({
   *   where: {
   *     // ... filter to delete one DocumentPair
   *   }
   * })
   * 
   */
  delete<T extends DocumentPairDeleteArgs>(args: Prisma.SelectSubset<T, DocumentPairDeleteArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DocumentPair.
   * @param {DocumentPairUpdateArgs} args - Arguments to update one DocumentPair.
   * @example
   * // Update one DocumentPair
   * const documentPair = await prisma.documentPair.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DocumentPairUpdateArgs>(args: Prisma.SelectSubset<T, DocumentPairUpdateArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DocumentPairs.
   * @param {DocumentPairDeleteManyArgs} args - Arguments to filter DocumentPairs to delete.
   * @example
   * // Delete a few DocumentPairs
   * const { count } = await prisma.documentPair.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DocumentPairDeleteManyArgs>(args?: Prisma.SelectSubset<T, DocumentPairDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentPairs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DocumentPairs
   * const documentPair = await prisma.documentPair.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DocumentPairUpdateManyArgs>(args: Prisma.SelectSubset<T, DocumentPairUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentPairs and returns the data updated in the database.
   * @param {DocumentPairUpdateManyAndReturnArgs} args - Arguments to update many DocumentPairs.
   * @example
   * // Update many DocumentPairs
   * const documentPair = await prisma.documentPair.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DocumentPairs and only return the `id`
   * const documentPairWithIdOnly = await prisma.documentPair.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DocumentPairUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DocumentPairUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DocumentPair.
   * @param {DocumentPairUpsertArgs} args - Arguments to update or create a DocumentPair.
   * @example
   * // Update or create a DocumentPair
   * const documentPair = await prisma.documentPair.upsert({
   *   create: {
   *     // ... data to create a DocumentPair
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DocumentPair we want to update
   *   }
   * })
   */
  upsert<T extends DocumentPairUpsertArgs>(args: Prisma.SelectSubset<T, DocumentPairUpsertArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DocumentPairs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairCountArgs} args - Arguments to filter DocumentPairs to count.
   * @example
   * // Count the number of DocumentPairs
   * const count = await prisma.documentPair.count({
   *   where: {
   *     // ... the filter for the DocumentPairs we want to count
   *   }
   * })
  **/
  count<T extends DocumentPairCountArgs>(
    args?: Prisma.Subset<T, DocumentPairCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DocumentPairCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DocumentPair.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DocumentPairAggregateArgs>(args: Prisma.Subset<T, DocumentPairAggregateArgs>): Prisma.PrismaPromise<GetDocumentPairAggregateType<T>>

  /**
   * Group by DocumentPair.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentPairGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DocumentPairGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DocumentPairGroupByArgs['orderBy'] }
      : { orderBy?: DocumentPairGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DocumentPairGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDocumentPairGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DocumentPair model
 */
readonly fields: DocumentPairFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DocumentPair.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DocumentPairClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.DocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentClient<runtime.Types.Result.GetResult<Prisma.$DocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  invoice<T extends Prisma.DocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentClient<runtime.Types.Result.GetResult<Prisma.$DocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  validations<T extends Prisma.DocumentPair$validationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentPair$validationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  summary<T extends Prisma.DocumentPair$summaryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentPair$summaryArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DocumentPair model
 */
export interface DocumentPairFieldRefs {
  readonly id: Prisma.FieldRef<"DocumentPair", 'String'>
  readonly orderId: Prisma.FieldRef<"DocumentPair", 'String'>
  readonly invoiceId: Prisma.FieldRef<"DocumentPair", 'String'>
  readonly createdAt: Prisma.FieldRef<"DocumentPair", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DocumentPair findUnique
 */
export type DocumentPairFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * Filter, which DocumentPair to fetch.
   */
  where: Prisma.DocumentPairWhereUniqueInput
}

/**
 * DocumentPair findUniqueOrThrow
 */
export type DocumentPairFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * Filter, which DocumentPair to fetch.
   */
  where: Prisma.DocumentPairWhereUniqueInput
}

/**
 * DocumentPair findFirst
 */
export type DocumentPairFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * Filter, which DocumentPair to fetch.
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentPairs to fetch.
   */
  orderBy?: Prisma.DocumentPairOrderByWithRelationInput | Prisma.DocumentPairOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentPairs.
   */
  cursor?: Prisma.DocumentPairWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentPairs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentPairs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentPairs.
   */
  distinct?: Prisma.DocumentPairScalarFieldEnum | Prisma.DocumentPairScalarFieldEnum[]
}

/**
 * DocumentPair findFirstOrThrow
 */
export type DocumentPairFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * Filter, which DocumentPair to fetch.
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentPairs to fetch.
   */
  orderBy?: Prisma.DocumentPairOrderByWithRelationInput | Prisma.DocumentPairOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentPairs.
   */
  cursor?: Prisma.DocumentPairWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentPairs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentPairs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentPairs.
   */
  distinct?: Prisma.DocumentPairScalarFieldEnum | Prisma.DocumentPairScalarFieldEnum[]
}

/**
 * DocumentPair findMany
 */
export type DocumentPairFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * Filter, which DocumentPairs to fetch.
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentPairs to fetch.
   */
  orderBy?: Prisma.DocumentPairOrderByWithRelationInput | Prisma.DocumentPairOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DocumentPairs.
   */
  cursor?: Prisma.DocumentPairWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentPairs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentPairs.
   */
  skip?: number
  distinct?: Prisma.DocumentPairScalarFieldEnum | Prisma.DocumentPairScalarFieldEnum[]
}

/**
 * DocumentPair create
 */
export type DocumentPairCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * The data needed to create a DocumentPair.
   */
  data: Prisma.XOR<Prisma.DocumentPairCreateInput, Prisma.DocumentPairUncheckedCreateInput>
}

/**
 * DocumentPair createMany
 */
export type DocumentPairCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DocumentPairs.
   */
  data: Prisma.DocumentPairCreateManyInput | Prisma.DocumentPairCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DocumentPair createManyAndReturn
 */
export type DocumentPairCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * The data used to create many DocumentPairs.
   */
  data: Prisma.DocumentPairCreateManyInput | Prisma.DocumentPairCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DocumentPair update
 */
export type DocumentPairUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * The data needed to update a DocumentPair.
   */
  data: Prisma.XOR<Prisma.DocumentPairUpdateInput, Prisma.DocumentPairUncheckedUpdateInput>
  /**
   * Choose, which DocumentPair to update.
   */
  where: Prisma.DocumentPairWhereUniqueInput
}

/**
 * DocumentPair updateMany
 */
export type DocumentPairUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DocumentPairs.
   */
  data: Prisma.XOR<Prisma.DocumentPairUpdateManyMutationInput, Prisma.DocumentPairUncheckedUpdateManyInput>
  /**
   * Filter which DocumentPairs to update
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * Limit how many DocumentPairs to update.
   */
  limit?: number
}

/**
 * DocumentPair updateManyAndReturn
 */
export type DocumentPairUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * The data used to update DocumentPairs.
   */
  data: Prisma.XOR<Prisma.DocumentPairUpdateManyMutationInput, Prisma.DocumentPairUncheckedUpdateManyInput>
  /**
   * Filter which DocumentPairs to update
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * Limit how many DocumentPairs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DocumentPair upsert
 */
export type DocumentPairUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * The filter to search for the DocumentPair to update in case it exists.
   */
  where: Prisma.DocumentPairWhereUniqueInput
  /**
   * In case the DocumentPair found by the `where` argument doesn't exist, create a new DocumentPair with this data.
   */
  create: Prisma.XOR<Prisma.DocumentPairCreateInput, Prisma.DocumentPairUncheckedCreateInput>
  /**
   * In case the DocumentPair was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DocumentPairUpdateInput, Prisma.DocumentPairUncheckedUpdateInput>
}

/**
 * DocumentPair delete
 */
export type DocumentPairDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
  /**
   * Filter which DocumentPair to delete.
   */
  where: Prisma.DocumentPairWhereUniqueInput
}

/**
 * DocumentPair deleteMany
 */
export type DocumentPairDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentPairs to delete
   */
  where?: Prisma.DocumentPairWhereInput
  /**
   * Limit how many DocumentPairs to delete.
   */
  limit?: number
}

/**
 * DocumentPair.validations
 */
export type DocumentPair$validationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationResult
   */
  select?: Prisma.ValidationResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationResult
   */
  omit?: Prisma.ValidationResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationResultInclude<ExtArgs> | null
  where?: Prisma.ValidationResultWhereInput
  orderBy?: Prisma.ValidationResultOrderByWithRelationInput | Prisma.ValidationResultOrderByWithRelationInput[]
  cursor?: Prisma.ValidationResultWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ValidationResultScalarFieldEnum | Prisma.ValidationResultScalarFieldEnum[]
}

/**
 * DocumentPair.summary
 */
export type DocumentPair$summaryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  where?: Prisma.ValidationSummaryWhereInput
}

/**
 * DocumentPair without action
 */
export type DocumentPairDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentPair
   */
  select?: Prisma.DocumentPairSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentPair
   */
  omit?: Prisma.DocumentPairOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentPairInclude<ExtArgs> | null
}
