
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ValidationSummary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ValidationSummary
 * 
 */
export type ValidationSummaryModel = runtime.Types.Result.DefaultSelection<Prisma.$ValidationSummaryPayload>

export type AggregateValidationSummary = {
  _count: ValidationSummaryCountAggregateOutputType | null
  _min: ValidationSummaryMinAggregateOutputType | null
  _max: ValidationSummaryMaxAggregateOutputType | null
}

export type ValidationSummaryMinAggregateOutputType = {
  id: string | null
  pairId: string | null
  itemsStatus: string | null
  vatStatus: string | null
  datesStatus: string | null
  totalsStatus: string | null
  finalStatus: string | null
}

export type ValidationSummaryMaxAggregateOutputType = {
  id: string | null
  pairId: string | null
  itemsStatus: string | null
  vatStatus: string | null
  datesStatus: string | null
  totalsStatus: string | null
  finalStatus: string | null
}

export type ValidationSummaryCountAggregateOutputType = {
  id: number
  pairId: number
  itemsStatus: number
  vatStatus: number
  datesStatus: number
  totalsStatus: number
  finalStatus: number
  _all: number
}


export type ValidationSummaryMinAggregateInputType = {
  id?: true
  pairId?: true
  itemsStatus?: true
  vatStatus?: true
  datesStatus?: true
  totalsStatus?: true
  finalStatus?: true
}

export type ValidationSummaryMaxAggregateInputType = {
  id?: true
  pairId?: true
  itemsStatus?: true
  vatStatus?: true
  datesStatus?: true
  totalsStatus?: true
  finalStatus?: true
}

export type ValidationSummaryCountAggregateInputType = {
  id?: true
  pairId?: true
  itemsStatus?: true
  vatStatus?: true
  datesStatus?: true
  totalsStatus?: true
  finalStatus?: true
  _all?: true
}

export type ValidationSummaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ValidationSummary to aggregate.
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationSummaries to fetch.
   */
  orderBy?: Prisma.ValidationSummaryOrderByWithRelationInput | Prisma.ValidationSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ValidationSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ValidationSummaries
  **/
  _count?: true | ValidationSummaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ValidationSummaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ValidationSummaryMaxAggregateInputType
}

export type GetValidationSummaryAggregateType<T extends ValidationSummaryAggregateArgs> = {
      [P in keyof T & keyof AggregateValidationSummary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateValidationSummary[P]>
    : Prisma.GetScalarType<T[P], AggregateValidationSummary[P]>
}




export type ValidationSummaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ValidationSummaryWhereInput
  orderBy?: Prisma.ValidationSummaryOrderByWithAggregationInput | Prisma.ValidationSummaryOrderByWithAggregationInput[]
  by: Prisma.ValidationSummaryScalarFieldEnum[] | Prisma.ValidationSummaryScalarFieldEnum
  having?: Prisma.ValidationSummaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ValidationSummaryCountAggregateInputType | true
  _min?: ValidationSummaryMinAggregateInputType
  _max?: ValidationSummaryMaxAggregateInputType
}

export type ValidationSummaryGroupByOutputType = {
  id: string
  pairId: string
  itemsStatus: string
  vatStatus: string
  datesStatus: string
  totalsStatus: string
  finalStatus: string
  _count: ValidationSummaryCountAggregateOutputType | null
  _min: ValidationSummaryMinAggregateOutputType | null
  _max: ValidationSummaryMaxAggregateOutputType | null
}

type GetValidationSummaryGroupByPayload<T extends ValidationSummaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ValidationSummaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ValidationSummaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ValidationSummaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ValidationSummaryGroupByOutputType[P]>
      }
    >
  >



export type ValidationSummaryWhereInput = {
  AND?: Prisma.ValidationSummaryWhereInput | Prisma.ValidationSummaryWhereInput[]
  OR?: Prisma.ValidationSummaryWhereInput[]
  NOT?: Prisma.ValidationSummaryWhereInput | Prisma.ValidationSummaryWhereInput[]
  id?: Prisma.StringFilter<"ValidationSummary"> | string
  pairId?: Prisma.StringFilter<"ValidationSummary"> | string
  itemsStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  vatStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  datesStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  totalsStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  finalStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  pair?: Prisma.XOR<Prisma.DocumentPairScalarRelationFilter, Prisma.DocumentPairWhereInput>
}

export type ValidationSummaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pairId?: Prisma.SortOrder
  itemsStatus?: Prisma.SortOrder
  vatStatus?: Prisma.SortOrder
  datesStatus?: Prisma.SortOrder
  totalsStatus?: Prisma.SortOrder
  finalStatus?: Prisma.SortOrder
  pair?: Prisma.DocumentPairOrderByWithRelationInput
}

export type ValidationSummaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  pairId?: string
  AND?: Prisma.ValidationSummaryWhereInput | Prisma.ValidationSummaryWhereInput[]
  OR?: Prisma.ValidationSummaryWhereInput[]
  NOT?: Prisma.ValidationSummaryWhereInput | Prisma.ValidationSummaryWhereInput[]
  itemsStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  vatStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  datesStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  totalsStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  finalStatus?: Prisma.StringFilter<"ValidationSummary"> | string
  pair?: Prisma.XOR<Prisma.DocumentPairScalarRelationFilter, Prisma.DocumentPairWhereInput>
}, "id" | "pairId">

export type ValidationSummaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pairId?: Prisma.SortOrder
  itemsStatus?: Prisma.SortOrder
  vatStatus?: Prisma.SortOrder
  datesStatus?: Prisma.SortOrder
  totalsStatus?: Prisma.SortOrder
  finalStatus?: Prisma.SortOrder
  _count?: Prisma.ValidationSummaryCountOrderByAggregateInput
  _max?: Prisma.ValidationSummaryMaxOrderByAggregateInput
  _min?: Prisma.ValidationSummaryMinOrderByAggregateInput
}

export type ValidationSummaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ValidationSummaryScalarWhereWithAggregatesInput | Prisma.ValidationSummaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ValidationSummaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ValidationSummaryScalarWhereWithAggregatesInput | Prisma.ValidationSummaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
  pairId?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
  itemsStatus?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
  vatStatus?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
  datesStatus?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
  totalsStatus?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
  finalStatus?: Prisma.StringWithAggregatesFilter<"ValidationSummary"> | string
}

export type ValidationSummaryCreateInput = {
  id?: string
  itemsStatus: string
  vatStatus: string
  datesStatus: string
  totalsStatus: string
  finalStatus: string
  pair: Prisma.DocumentPairCreateNestedOneWithoutSummaryInput
}

export type ValidationSummaryUncheckedCreateInput = {
  id?: string
  pairId: string
  itemsStatus: string
  vatStatus: string
  datesStatus: string
  totalsStatus: string
  finalStatus: string
}

export type ValidationSummaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  vatStatus?: Prisma.StringFieldUpdateOperationsInput | string
  datesStatus?: Prisma.StringFieldUpdateOperationsInput | string
  totalsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  finalStatus?: Prisma.StringFieldUpdateOperationsInput | string
  pair?: Prisma.DocumentPairUpdateOneRequiredWithoutSummaryNestedInput
}

export type ValidationSummaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pairId?: Prisma.StringFieldUpdateOperationsInput | string
  itemsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  vatStatus?: Prisma.StringFieldUpdateOperationsInput | string
  datesStatus?: Prisma.StringFieldUpdateOperationsInput | string
  totalsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  finalStatus?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ValidationSummaryCreateManyInput = {
  id?: string
  pairId: string
  itemsStatus: string
  vatStatus: string
  datesStatus: string
  totalsStatus: string
  finalStatus: string
}

export type ValidationSummaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  vatStatus?: Prisma.StringFieldUpdateOperationsInput | string
  datesStatus?: Prisma.StringFieldUpdateOperationsInput | string
  totalsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  finalStatus?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ValidationSummaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pairId?: Prisma.StringFieldUpdateOperationsInput | string
  itemsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  vatStatus?: Prisma.StringFieldUpdateOperationsInput | string
  datesStatus?: Prisma.StringFieldUpdateOperationsInput | string
  totalsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  finalStatus?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ValidationSummaryNullableScalarRelationFilter = {
  is?: Prisma.ValidationSummaryWhereInput | null
  isNot?: Prisma.ValidationSummaryWhereInput | null
}

export type ValidationSummaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pairId?: Prisma.SortOrder
  itemsStatus?: Prisma.SortOrder
  vatStatus?: Prisma.SortOrder
  datesStatus?: Prisma.SortOrder
  totalsStatus?: Prisma.SortOrder
  finalStatus?: Prisma.SortOrder
}

export type ValidationSummaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pairId?: Prisma.SortOrder
  itemsStatus?: Prisma.SortOrder
  vatStatus?: Prisma.SortOrder
  datesStatus?: Prisma.SortOrder
  totalsStatus?: Prisma.SortOrder
  finalStatus?: Prisma.SortOrder
}

export type ValidationSummaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pairId?: Prisma.SortOrder
  itemsStatus?: Prisma.SortOrder
  vatStatus?: Prisma.SortOrder
  datesStatus?: Prisma.SortOrder
  totalsStatus?: Prisma.SortOrder
  finalStatus?: Prisma.SortOrder
}

export type ValidationSummaryCreateNestedOneWithoutPairInput = {
  create?: Prisma.XOR<Prisma.ValidationSummaryCreateWithoutPairInput, Prisma.ValidationSummaryUncheckedCreateWithoutPairInput>
  connectOrCreate?: Prisma.ValidationSummaryCreateOrConnectWithoutPairInput
  connect?: Prisma.ValidationSummaryWhereUniqueInput
}

export type ValidationSummaryUncheckedCreateNestedOneWithoutPairInput = {
  create?: Prisma.XOR<Prisma.ValidationSummaryCreateWithoutPairInput, Prisma.ValidationSummaryUncheckedCreateWithoutPairInput>
  connectOrCreate?: Prisma.ValidationSummaryCreateOrConnectWithoutPairInput
  connect?: Prisma.ValidationSummaryWhereUniqueInput
}

export type ValidationSummaryUpdateOneWithoutPairNestedInput = {
  create?: Prisma.XOR<Prisma.ValidationSummaryCreateWithoutPairInput, Prisma.ValidationSummaryUncheckedCreateWithoutPairInput>
  connectOrCreate?: Prisma.ValidationSummaryCreateOrConnectWithoutPairInput
  upsert?: Prisma.ValidationSummaryUpsertWithoutPairInput
  disconnect?: Prisma.ValidationSummaryWhereInput | boolean
  delete?: Prisma.ValidationSummaryWhereInput | boolean
  connect?: Prisma.ValidationSummaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ValidationSummaryUpdateToOneWithWhereWithoutPairInput, Prisma.ValidationSummaryUpdateWithoutPairInput>, Prisma.ValidationSummaryUncheckedUpdateWithoutPairInput>
}

export type ValidationSummaryUncheckedUpdateOneWithoutPairNestedInput = {
  create?: Prisma.XOR<Prisma.ValidationSummaryCreateWithoutPairInput, Prisma.ValidationSummaryUncheckedCreateWithoutPairInput>
  connectOrCreate?: Prisma.ValidationSummaryCreateOrConnectWithoutPairInput
  upsert?: Prisma.ValidationSummaryUpsertWithoutPairInput
  disconnect?: Prisma.ValidationSummaryWhereInput | boolean
  delete?: Prisma.ValidationSummaryWhereInput | boolean
  connect?: Prisma.ValidationSummaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ValidationSummaryUpdateToOneWithWhereWithoutPairInput, Prisma.ValidationSummaryUpdateWithoutPairInput>, Prisma.ValidationSummaryUncheckedUpdateWithoutPairInput>
}

export type ValidationSummaryCreateWithoutPairInput = {
  id?: string
  itemsStatus: string
  vatStatus: string
  datesStatus: string
  totalsStatus: string
  finalStatus: string
}

export type ValidationSummaryUncheckedCreateWithoutPairInput = {
  id?: string
  itemsStatus: string
  vatStatus: string
  datesStatus: string
  totalsStatus: string
  finalStatus: string
}

export type ValidationSummaryCreateOrConnectWithoutPairInput = {
  where: Prisma.ValidationSummaryWhereUniqueInput
  create: Prisma.XOR<Prisma.ValidationSummaryCreateWithoutPairInput, Prisma.ValidationSummaryUncheckedCreateWithoutPairInput>
}

export type ValidationSummaryUpsertWithoutPairInput = {
  update: Prisma.XOR<Prisma.ValidationSummaryUpdateWithoutPairInput, Prisma.ValidationSummaryUncheckedUpdateWithoutPairInput>
  create: Prisma.XOR<Prisma.ValidationSummaryCreateWithoutPairInput, Prisma.ValidationSummaryUncheckedCreateWithoutPairInput>
  where?: Prisma.ValidationSummaryWhereInput
}

export type ValidationSummaryUpdateToOneWithWhereWithoutPairInput = {
  where?: Prisma.ValidationSummaryWhereInput
  data: Prisma.XOR<Prisma.ValidationSummaryUpdateWithoutPairInput, Prisma.ValidationSummaryUncheckedUpdateWithoutPairInput>
}

export type ValidationSummaryUpdateWithoutPairInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  vatStatus?: Prisma.StringFieldUpdateOperationsInput | string
  datesStatus?: Prisma.StringFieldUpdateOperationsInput | string
  totalsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  finalStatus?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ValidationSummaryUncheckedUpdateWithoutPairInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  vatStatus?: Prisma.StringFieldUpdateOperationsInput | string
  datesStatus?: Prisma.StringFieldUpdateOperationsInput | string
  totalsStatus?: Prisma.StringFieldUpdateOperationsInput | string
  finalStatus?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ValidationSummarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pairId?: boolean
  itemsStatus?: boolean
  vatStatus?: boolean
  datesStatus?: boolean
  totalsStatus?: boolean
  finalStatus?: boolean
  pair?: boolean | Prisma.DocumentPairDefaultArgs<ExtArgs>
}, ExtArgs["result"]["validationSummary"]>

export type ValidationSummarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pairId?: boolean
  itemsStatus?: boolean
  vatStatus?: boolean
  datesStatus?: boolean
  totalsStatus?: boolean
  finalStatus?: boolean
  pair?: boolean | Prisma.DocumentPairDefaultArgs<ExtArgs>
}, ExtArgs["result"]["validationSummary"]>

export type ValidationSummarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pairId?: boolean
  itemsStatus?: boolean
  vatStatus?: boolean
  datesStatus?: boolean
  totalsStatus?: boolean
  finalStatus?: boolean
  pair?: boolean | Prisma.DocumentPairDefaultArgs<ExtArgs>
}, ExtArgs["result"]["validationSummary"]>

export type ValidationSummarySelectScalar = {
  id?: boolean
  pairId?: boolean
  itemsStatus?: boolean
  vatStatus?: boolean
  datesStatus?: boolean
  totalsStatus?: boolean
  finalStatus?: boolean
}

export type ValidationSummaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pairId" | "itemsStatus" | "vatStatus" | "datesStatus" | "totalsStatus" | "finalStatus", ExtArgs["result"]["validationSummary"]>
export type ValidationSummaryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pair?: boolean | Prisma.DocumentPairDefaultArgs<ExtArgs>
}
export type ValidationSummaryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pair?: boolean | Prisma.DocumentPairDefaultArgs<ExtArgs>
}
export type ValidationSummaryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pair?: boolean | Prisma.DocumentPairDefaultArgs<ExtArgs>
}

export type $ValidationSummaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ValidationSummary"
  objects: {
    pair: Prisma.$DocumentPairPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pairId: string
    itemsStatus: string
    vatStatus: string
    datesStatus: string
    totalsStatus: string
    finalStatus: string
  }, ExtArgs["result"]["validationSummary"]>
  composites: {}
}

export type ValidationSummaryGetPayload<S extends boolean | null | undefined | ValidationSummaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload, S>

export type ValidationSummaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ValidationSummaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ValidationSummaryCountAggregateInputType | true
  }

export interface ValidationSummaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ValidationSummary'], meta: { name: 'ValidationSummary' } }
  /**
   * Find zero or one ValidationSummary that matches the filter.
   * @param {ValidationSummaryFindUniqueArgs} args - Arguments to find a ValidationSummary
   * @example
   * // Get one ValidationSummary
   * const validationSummary = await prisma.validationSummary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ValidationSummaryFindUniqueArgs>(args: Prisma.SelectSubset<T, ValidationSummaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ValidationSummary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ValidationSummaryFindUniqueOrThrowArgs} args - Arguments to find a ValidationSummary
   * @example
   * // Get one ValidationSummary
   * const validationSummary = await prisma.validationSummary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ValidationSummaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ValidationSummaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ValidationSummary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryFindFirstArgs} args - Arguments to find a ValidationSummary
   * @example
   * // Get one ValidationSummary
   * const validationSummary = await prisma.validationSummary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ValidationSummaryFindFirstArgs>(args?: Prisma.SelectSubset<T, ValidationSummaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ValidationSummary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryFindFirstOrThrowArgs} args - Arguments to find a ValidationSummary
   * @example
   * // Get one ValidationSummary
   * const validationSummary = await prisma.validationSummary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ValidationSummaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ValidationSummaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ValidationSummaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ValidationSummaries
   * const validationSummaries = await prisma.validationSummary.findMany()
   * 
   * // Get first 10 ValidationSummaries
   * const validationSummaries = await prisma.validationSummary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const validationSummaryWithIdOnly = await prisma.validationSummary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ValidationSummaryFindManyArgs>(args?: Prisma.SelectSubset<T, ValidationSummaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ValidationSummary.
   * @param {ValidationSummaryCreateArgs} args - Arguments to create a ValidationSummary.
   * @example
   * // Create one ValidationSummary
   * const ValidationSummary = await prisma.validationSummary.create({
   *   data: {
   *     // ... data to create a ValidationSummary
   *   }
   * })
   * 
   */
  create<T extends ValidationSummaryCreateArgs>(args: Prisma.SelectSubset<T, ValidationSummaryCreateArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ValidationSummaries.
   * @param {ValidationSummaryCreateManyArgs} args - Arguments to create many ValidationSummaries.
   * @example
   * // Create many ValidationSummaries
   * const validationSummary = await prisma.validationSummary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ValidationSummaryCreateManyArgs>(args?: Prisma.SelectSubset<T, ValidationSummaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ValidationSummaries and returns the data saved in the database.
   * @param {ValidationSummaryCreateManyAndReturnArgs} args - Arguments to create many ValidationSummaries.
   * @example
   * // Create many ValidationSummaries
   * const validationSummary = await prisma.validationSummary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ValidationSummaries and only return the `id`
   * const validationSummaryWithIdOnly = await prisma.validationSummary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ValidationSummaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ValidationSummaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ValidationSummary.
   * @param {ValidationSummaryDeleteArgs} args - Arguments to delete one ValidationSummary.
   * @example
   * // Delete one ValidationSummary
   * const ValidationSummary = await prisma.validationSummary.delete({
   *   where: {
   *     // ... filter to delete one ValidationSummary
   *   }
   * })
   * 
   */
  delete<T extends ValidationSummaryDeleteArgs>(args: Prisma.SelectSubset<T, ValidationSummaryDeleteArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ValidationSummary.
   * @param {ValidationSummaryUpdateArgs} args - Arguments to update one ValidationSummary.
   * @example
   * // Update one ValidationSummary
   * const validationSummary = await prisma.validationSummary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ValidationSummaryUpdateArgs>(args: Prisma.SelectSubset<T, ValidationSummaryUpdateArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ValidationSummaries.
   * @param {ValidationSummaryDeleteManyArgs} args - Arguments to filter ValidationSummaries to delete.
   * @example
   * // Delete a few ValidationSummaries
   * const { count } = await prisma.validationSummary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ValidationSummaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ValidationSummaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ValidationSummaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ValidationSummaries
   * const validationSummary = await prisma.validationSummary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ValidationSummaryUpdateManyArgs>(args: Prisma.SelectSubset<T, ValidationSummaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ValidationSummaries and returns the data updated in the database.
   * @param {ValidationSummaryUpdateManyAndReturnArgs} args - Arguments to update many ValidationSummaries.
   * @example
   * // Update many ValidationSummaries
   * const validationSummary = await prisma.validationSummary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ValidationSummaries and only return the `id`
   * const validationSummaryWithIdOnly = await prisma.validationSummary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ValidationSummaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ValidationSummaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ValidationSummary.
   * @param {ValidationSummaryUpsertArgs} args - Arguments to update or create a ValidationSummary.
   * @example
   * // Update or create a ValidationSummary
   * const validationSummary = await prisma.validationSummary.upsert({
   *   create: {
   *     // ... data to create a ValidationSummary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ValidationSummary we want to update
   *   }
   * })
   */
  upsert<T extends ValidationSummaryUpsertArgs>(args: Prisma.SelectSubset<T, ValidationSummaryUpsertArgs<ExtArgs>>): Prisma.Prisma__ValidationSummaryClient<runtime.Types.Result.GetResult<Prisma.$ValidationSummaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ValidationSummaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryCountArgs} args - Arguments to filter ValidationSummaries to count.
   * @example
   * // Count the number of ValidationSummaries
   * const count = await prisma.validationSummary.count({
   *   where: {
   *     // ... the filter for the ValidationSummaries we want to count
   *   }
   * })
  **/
  count<T extends ValidationSummaryCountArgs>(
    args?: Prisma.Subset<T, ValidationSummaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ValidationSummaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ValidationSummary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ValidationSummaryAggregateArgs>(args: Prisma.Subset<T, ValidationSummaryAggregateArgs>): Prisma.PrismaPromise<GetValidationSummaryAggregateType<T>>

  /**
   * Group by ValidationSummary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationSummaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ValidationSummaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ValidationSummaryGroupByArgs['orderBy'] }
      : { orderBy?: ValidationSummaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ValidationSummaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetValidationSummaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ValidationSummary model
 */
readonly fields: ValidationSummaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ValidationSummary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ValidationSummaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pair<T extends Prisma.DocumentPairDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentPairDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentPairClient<runtime.Types.Result.GetResult<Prisma.$DocumentPairPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ValidationSummary model
 */
export interface ValidationSummaryFieldRefs {
  readonly id: Prisma.FieldRef<"ValidationSummary", 'String'>
  readonly pairId: Prisma.FieldRef<"ValidationSummary", 'String'>
  readonly itemsStatus: Prisma.FieldRef<"ValidationSummary", 'String'>
  readonly vatStatus: Prisma.FieldRef<"ValidationSummary", 'String'>
  readonly datesStatus: Prisma.FieldRef<"ValidationSummary", 'String'>
  readonly totalsStatus: Prisma.FieldRef<"ValidationSummary", 'String'>
  readonly finalStatus: Prisma.FieldRef<"ValidationSummary", 'String'>
}
    

// Custom InputTypes
/**
 * ValidationSummary findUnique
 */
export type ValidationSummaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * Filter, which ValidationSummary to fetch.
   */
  where: Prisma.ValidationSummaryWhereUniqueInput
}

/**
 * ValidationSummary findUniqueOrThrow
 */
export type ValidationSummaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * Filter, which ValidationSummary to fetch.
   */
  where: Prisma.ValidationSummaryWhereUniqueInput
}

/**
 * ValidationSummary findFirst
 */
export type ValidationSummaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * Filter, which ValidationSummary to fetch.
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationSummaries to fetch.
   */
  orderBy?: Prisma.ValidationSummaryOrderByWithRelationInput | Prisma.ValidationSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ValidationSummaries.
   */
  cursor?: Prisma.ValidationSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationSummaries.
   */
  distinct?: Prisma.ValidationSummaryScalarFieldEnum | Prisma.ValidationSummaryScalarFieldEnum[]
}

/**
 * ValidationSummary findFirstOrThrow
 */
export type ValidationSummaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * Filter, which ValidationSummary to fetch.
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationSummaries to fetch.
   */
  orderBy?: Prisma.ValidationSummaryOrderByWithRelationInput | Prisma.ValidationSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ValidationSummaries.
   */
  cursor?: Prisma.ValidationSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationSummaries.
   */
  distinct?: Prisma.ValidationSummaryScalarFieldEnum | Prisma.ValidationSummaryScalarFieldEnum[]
}

/**
 * ValidationSummary findMany
 */
export type ValidationSummaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * Filter, which ValidationSummaries to fetch.
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationSummaries to fetch.
   */
  orderBy?: Prisma.ValidationSummaryOrderByWithRelationInput | Prisma.ValidationSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ValidationSummaries.
   */
  cursor?: Prisma.ValidationSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationSummaries.
   */
  skip?: number
  distinct?: Prisma.ValidationSummaryScalarFieldEnum | Prisma.ValidationSummaryScalarFieldEnum[]
}

/**
 * ValidationSummary create
 */
export type ValidationSummaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * The data needed to create a ValidationSummary.
   */
  data: Prisma.XOR<Prisma.ValidationSummaryCreateInput, Prisma.ValidationSummaryUncheckedCreateInput>
}

/**
 * ValidationSummary createMany
 */
export type ValidationSummaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ValidationSummaries.
   */
  data: Prisma.ValidationSummaryCreateManyInput | Prisma.ValidationSummaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ValidationSummary createManyAndReturn
 */
export type ValidationSummaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * The data used to create many ValidationSummaries.
   */
  data: Prisma.ValidationSummaryCreateManyInput | Prisma.ValidationSummaryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ValidationSummary update
 */
export type ValidationSummaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * The data needed to update a ValidationSummary.
   */
  data: Prisma.XOR<Prisma.ValidationSummaryUpdateInput, Prisma.ValidationSummaryUncheckedUpdateInput>
  /**
   * Choose, which ValidationSummary to update.
   */
  where: Prisma.ValidationSummaryWhereUniqueInput
}

/**
 * ValidationSummary updateMany
 */
export type ValidationSummaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ValidationSummaries.
   */
  data: Prisma.XOR<Prisma.ValidationSummaryUpdateManyMutationInput, Prisma.ValidationSummaryUncheckedUpdateManyInput>
  /**
   * Filter which ValidationSummaries to update
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * Limit how many ValidationSummaries to update.
   */
  limit?: number
}

/**
 * ValidationSummary updateManyAndReturn
 */
export type ValidationSummaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * The data used to update ValidationSummaries.
   */
  data: Prisma.XOR<Prisma.ValidationSummaryUpdateManyMutationInput, Prisma.ValidationSummaryUncheckedUpdateManyInput>
  /**
   * Filter which ValidationSummaries to update
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * Limit how many ValidationSummaries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ValidationSummary upsert
 */
export type ValidationSummaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * The filter to search for the ValidationSummary to update in case it exists.
   */
  where: Prisma.ValidationSummaryWhereUniqueInput
  /**
   * In case the ValidationSummary found by the `where` argument doesn't exist, create a new ValidationSummary with this data.
   */
  create: Prisma.XOR<Prisma.ValidationSummaryCreateInput, Prisma.ValidationSummaryUncheckedCreateInput>
  /**
   * In case the ValidationSummary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ValidationSummaryUpdateInput, Prisma.ValidationSummaryUncheckedUpdateInput>
}

/**
 * ValidationSummary delete
 */
export type ValidationSummaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
  /**
   * Filter which ValidationSummary to delete.
   */
  where: Prisma.ValidationSummaryWhereUniqueInput
}

/**
 * ValidationSummary deleteMany
 */
export type ValidationSummaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ValidationSummaries to delete
   */
  where?: Prisma.ValidationSummaryWhereInput
  /**
   * Limit how many ValidationSummaries to delete.
   */
  limit?: number
}

/**
 * ValidationSummary without action
 */
export type ValidationSummaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationSummary
   */
  select?: Prisma.ValidationSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationSummary
   */
  omit?: Prisma.ValidationSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationSummaryInclude<ExtArgs> | null
}
